### ISSUE TITLE
If !whitelisted then do not show `isClaimed` and `isExpired` and provide some feedback

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/lukso-claim-program#2]
If the address !isWhitelisted then do not show `isClaimed` and `isExpired` and provide some feedback

See 
<img width="525" alt="Screenshot 2024-01-16 at 16 10 05" src="https://github.com/dappnode/lukso-claim-program/assets/41727368/a10cc634-956b-4719-9ffd-3e03d73ee1b1">

**Comment by GiselleNessi** [comment]
this has been merged
